### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by sbfnk** [cmu-delphi/quantmod#4]
The name of the package conflicts with https://cran.r-project.org/web/packages/quantmod/index.html - so installing this breaks, for example, the `forecast` package.

Can the name be changed?

**Comment by ryantibs** [comment]
Thanks for pointing this out, and yes, I caught this a little while back.  So I changed the name to `quantgen` and moved it to this location: https://github.com/ryantibs/quantgen (since it's not really Delphi specific, it's just a general package on quantile modeling at this point).  This repo (cmu-delphi/quantmod) is not going to be updated anymore, and I'm going to delete it soon.
